### ISSUE TITLE
Search Facilities Text overlaps search box and is duplicated 

### ISSUE THREAD

**Issue by Shadey88** [linkvanproject/linkvan-web#27]
On Mobile or Tablet, the Search Box Text is duplicated and intrudes on search box

**Comment by Shadey88** [comment]
![60F473A6-C3E8-4670-9DFD-31DE0375E107](https://user-images.githubusercontent.com/100090188/165847533-7e26b42f-46e8-480a-b4fc-09e91ff508e2.png)

**Comment by andresouza** [comment]
It seems to be happening only in the Home Page

**Comment by andresouza** [comment]
The bug was fixed after upgrading `nextjs` to `v12` along with other plugins in this commit https://github.com/linkvanproject/linkvan-web/commit/795849cc608478f749e5ec2681073d22c3424c98
