### ISSUE TITLE
Mobile iPhone 8 or smaller the welcomes icons do not wrap 

### ISSUE THREAD

**Issue by Shadey88** [linkvanproject/linkvan-web#28]
On a small mobile screen if there are a lot of welcomes icons then some of the icons are lost on the right side as they do not wrap.
![71B74EC7-45FC-40F7-A588-F0077BA5BD37](https://user-images.githubusercontent.com/100090188/165848520-28be8a56-dcb3-4504-8b84-9f302049b4eb.jpeg)

**Comment by andresouza** [comment]
Example here https://linkvan-web.vercel.app/facilities/75

**Comment by andresouza** [comment]
Fixed here https://github.com/linkvanproject/linkvan-web/pull/80
