### ISSUE TITLE
The opening times do not display last digit of time

### ISSUE THREAD

**Issue by Shadey88** [linkvanproject/linkvan-web#29]
The opening time displays 8:0 am to 8:0 pm instead of 8:00am to 8:00pm
![1E457278-431C-4664-8E5F-BC1B4AD24173](https://user-images.githubusercontent.com/100090188/165848705-05095386-5831-4061-bde1-02a6a2bb676a.jpeg)

**Comment by andresouza** [comment]
Example here https://linkvan-web.vercel.app/facilities/75
