### ISSUE TITLE
Implement Google Analytics

### ISSUE THREAD

**Issue by andresouza** [linkvanproject/linkvan-web#33]
- Implement Google Analytics for the whole app;
- Track clicks on phone numbers;
- Constant session x short session: to track the amount of access to a specific user;
  - According to GA, If the user doesn't interact with the app for more than 30 min (TBD), a new session is created;
  - GA doesn't allow us to store the user location, so we will get the session ID from GA and use it to save the user location in our database;
- We will get the user's device info from GA;
- In Facilities page, add `sort` and `filter` to url so we can track in GA;

**Comment by fabionl** [comment]
To document our latest discussion.

Our current idea is to have a `ga_token` and a `token` sent on each call to the API, and the backend will save both as part of the analytics data.

`ga_token` comes from is the session generated and managed by GoogleAnalytics.

This is our planned workflow:
1. On the first call to the API, the frontend will take the GoogleAnalytics' session id and send to the backend at a `ga_token` and the `token` will be empty.
2. The backend receives a `ga_token` and as the `token` is empty, generates a new token.
3. The backend saves both as part of the analytics data.
4. The backend sends the result of the api call including the `token`.
5. The frontend receives the data and saves the token.
6. On the next call to the API, the frontend sends both `ga_token` and `token`.

Note: For now, we are not planning to make tokens dynamic. The Backend will generate one token if it doesn't receive one, and will keep resending the same token to the frontend. But to make this more flexible, the frontend will just keep sending the latest token received from the Backend.

**Comment by fabionl** [comment]
Updating with the actual implementation.

The backend is generating a `uuid` and a `session-token` and sending to the frontend.

- `uuid` - Is a 32 bytes random string and uniquely identify the current session.
- `session-token` - is a JWT token with a 30 minutes lifespan.

When a new request with an expired session-token is made, the backend automatically generates a new session-token and includes it in the responses.

These tokens are included in the response body under the `tokens` key, and also included in the response as a cookie under the name `_linkvan_tokens`.

The frontend can either keep and resend the cookies, or send the tokens as part of the query parameters using these same names:

`api/home?uuid=<uuid>&session-token=<session-token>`

Note: As of now, the query parameters take priority over the cookies.

**Comment by andresouza** [comment]
The logic was moved to cookies and we don't need the user `uuid`.
